### ISSUE TITLE
Let's use the GH Package registry

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#32]

**Comment by AfterNetwork** [comment]
@smileycreations15

**Comment by smileycreations15** [comment]
idk..

**Comment by AfterNetwork** [comment]
Just do it!

**Comment by smileycreations15** [comment]
idk

**Comment by smileycreations15** [comment]
okay

**Comment by AfterNetwork** [comment]
`// Step 1: Use `publishConfig` option in your package.json
"publishConfig": { "registry": "https://npm.pkg.github.com/" }
// Step 2: Authenticate
$ npm login --registry=https://npm.pkg.github.com/

// Step 3: Publish
$ npm publish`
