### ISSUE TITLE
revival of smile.js

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#37]
let's revive this.
cc @smileycreations15

**Comment by smileycreations15** [comment]
yeah

**Comment by AfterNetwork** [comment]
it hasn't been used for a while, and I suppose you have some free time?

**Comment by AfterNetwork** [comment]
also look at my PR.

**Comment by smileycreations15** [comment]
yes, + im making a 3d renderer, the next feature of smile.js
