### ISSUE TITLE
Blockchain upgrade.

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#38]
I just got a good idea. A blockchain feature for smile.js that could create a blockchain (virtually). Multiple blockchains, with different hashes.

**Comment by AfterNetwork** [comment]
cc @smileycreations15

**Comment by smileycreations15** [comment]
ye

**Comment by smileycreations15** [comment]
nice

**Comment by smileycreations15** [comment]
make a list and post updates to it

**Comment by AfterNetwork** [comment]
the list is in projects

**Comment by smileycreations15** [comment]
ok then

**Comment by smileycreations15** [comment]
just a sec
