### ISSUE TITLE
Revamp of Smile.JS.

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#39]
We should revamp some things, because the code's getting old.

**Comment by AfterNetwork** [comment]
cc @smileycreations15

**Comment by smileycreations15** [comment]
oki but dont ping me i am already getting notifs from email

**Comment by AfterNetwork** [comment]
Revamp main code, maybe the CSS engine, and some modules.

**Comment by smileycreations15** [comment]
wait.. im working on a 3d renderer
