### ISSUE TITLE
[PLEASE KEEP ON TOPIC] Windows Support for Smile.js

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#41]
I'm going to have to open a new thread after the "incident."

**Comment by AfterNetwork** [comment]
cc @smileycreations15

**Comment by smileycreations15** [comment]
How? This is cross-platform already. Node.js? There is no support for Windows atm.

**Comment by AfterNetwork** [comment]
> How? This is cross-platform already. Node.js? There is no support for Windows atm.

It's possible.
