### ISSUE TITLE
continue development on smile.js

### ISSUE THREAD

**Issue by AfterNetwork** [Semisol/Smile.js#52]
@Semisol @AfterNetwork @codacy-badger

**Comment by Semisol** [comment]
i want to do a new project

**Comment by AfterNetwork** [comment]
oook, how about a platform where people can visually create a simple game while we handle backend?

**Comment by Semisol** [comment]
hmm

**Comment by Semisol** [comment]
nah

**Comment by AfterNetwork** [comment]
idea: you know the saying one man's trash is another man's treasure?
well how about an infinite trash bin where people can view each others trash or private trashes?

**Comment by AfterNetwork** [comment]
@Semisol

**Comment by Semisol** [comment]
wot???

**Comment by Semisol** [comment]
game or what

**Comment by AfterNetwork** [comment]
a website

**Comment by AfterNetwork** [comment]
infinite trash bin

**Comment by AfterNetwork** [comment]
private or public files can be "trashed here"

**Comment by AfterNetwork** [comment]
@Semisol

**Comment by Semisol** [comment]
Okay

**Comment by Semisol** [comment]
sure @AfterNetwork

**Comment by AfterNetwork** [comment]
what, so you want to work on it?

**Comment by Semisol** [comment]
maybe @AfterNetwork

**Comment by Semisol** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
ok go on gitter @Semisol

**Comment by AfterNetwork** [comment]
![2020-08-24_17 52 50](https://user-images.githubusercontent.com/45772308/91110535-fcaa6480-e632-11ea-8577-91f33eaa80c5.png)
Remember the dropper battle with you using 32ks? Well I revamped the area to go entire island with a hospital. Nice, huh?
||@Semisol ||
